### PR TITLE
dashboard cmd: support local clusters on linux

### LINKED ISSUE #1127: CLI dashboard doesn't work with local cluster
**Description**
I cannot connect to local cluster using kyma dashboard.

**Expected result**
I can connect to local cluster

**Actual result**
When I open kyma dashboard I get following errors:
```
Could not load initial configuration
Could not find the requested route cluster/k3d-kyma/overview.
```

**Steps to reproduce**
Run:
```
kyma provision k3d
kyma dashboard
```

**Troubleshooting**
To solve this issue, the cli could have additiona flag `--local`, which adds additional docker parameter for busola startup command:
- Linux `--network=host`
- Docker for desktop `--env DOCKER_DESKTOP_CLUSTER=true`
More details are availabe here: https://github.com/kyma-project/busola#remedy

### PR DESCRIPTION
**Pull request by dennis-ge**
**Description**

Changes proposed in this pull request:

- start busola with the docker network flag in order to use the dashboard cmd with local clusters running on linux

**Related issue(s)**
Fixes #1127

### CODE REVIEW

File: cmd/kyma/dashboard/cmd.go [hunk 1]
```diff
@@ -128,6 +129,13 @@ func (cmd *command) initContainerRunOpts(envs []string) (docker.ContainerRunOpts
 		dashboardURL = fmt.Sprintf("%s?kubeconfigID=%s", dashboardURL, containerKubeconfigFilename)
 	}
 
+	if runtime.GOOS == "linux" {
+		if cmd.Verbose {
+			fmt.Printf("Operating System seems to be linux. Changing the Docker network mode to 'host'")
```
Comment (NHingerl) [inline cmd/kyma/dashboard/cmd.go:134]:
```suggestion
			fmt.Printf("Operating system seems to be Linux. Changing the Docker network mode to 'host'")
```

**Review by NHingerl — APPROVED** [review]

**Review by skhalash — APPROVED** [review]
