### PR TITLE
Fix error printing in case of timeout

### LINKED ISSUE #379: Failure reason not printed in case of timeout
**Description**

Kyma installation using CLI does not print the failure reason when the installation times out. 

An example timeout using CLI:
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-gardener-azure-integration/1229877680757805056/build-log.txt

An example timeout without CLI:
https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/7247/pre-master-kyma-gke-integration/1229777393908977665/build-log.txt

### PR DESCRIPTION
**Pull request by shorim**
**Description**

Changes proposed in this pull request:

- Fixing the command for error logging in case of timeout
- Printing the error in case that fetching installation error log has failed

**Related issue(s)**
Fixes #379

### CODE REVIEW

File: pkg/installation/installation.go [hunk 1]
```diff
@@ -594,7 +594,7 @@ func (i *Installation) waitForInstaller() error {
 		case <-timeout:
 			i.currentStep.Failure()
 			if err := i.printInstallationErrorLog(); err != nil {
-				fmt.Println("Error fetching installation error log, please manually check the status of the cluster.")
+				fmt.Println("Error fetching installation error log: ", err, "\nPlease manually check the status of the cluster")
```
Comment (clebs) [inline pkg/installation/installation.go]: Please use `fmt.Printf` here if you want to print a string containing the error.
This way is not clear what will be printed.

**Comment by clebs** [comment]
@shorim,
please sign the CLA, otherwise your PR can not be merged.
Thanks
