### PR TITLE
Fix repoUrl for parent-child git structure

### LINKED ISSUE #1765: Wrong repoUrl in moduletemplate.yaml in parent-child git structure
**Description**

In our use case we execute the `kyma alpha create module` command in a parent-child structure with 2 cloned Git repository.
```bash
(parent-git-code)
├── modules
├── child-git-code
```
1st Git related code (parent git-code): Pipeline related code.
2nd Git related code (child git-code): Kyma module related code

When we run the `kyma alpha create module` command from the `parent-git-code` directory and define the `child-git-code` relative path for kyma-cli command the generated module template contains the `parent` Git URL instead of `child` Git URL.

Related lines on this way:
```yaml
      - access:
          commit: 21**************
          repoUrl: https://github.****/kyma/parent-repo
```

Expected lines:
```yaml
      - access:
          commit: 21**************
          repoUrl: https://github.****/kyma-project/child-repo
```

Command we use:
```bash
kyma alpha create module \
                  --module-config-file ./child-git-code/config.yaml \
                  --path ./child-git-code \
                  --registry "************" \
                  --sec-scanners-config ./sec-config.yaml \
                  --module-archive-version-overwrite \
                  --output=moduletemplate.yaml \
                  --registry-cred-selector=*********\
                  --credentials oauth2accesstoken:********
```

**Version**: We used the unstable version which was available at 2023-09-12 08:00:00 CEST.
**OS**: Ubuntu 22.04 - Azure Pipeline

**Expected result**

moduletemplate.yaml
```yaml
      - access:
          commit: 21**************
          repoUrl: https://github.****/kyma-project/child-repo
```
**Actual result**

moduletemplate.yaml
```yaml
      - access:
          commit: 21**************
          repoUrl: https://github.****/kyma/parent-repo
```
**Steps to reproduce**

1. Clone a git repository as `parent` repository
2. Enter the cloned repository directory
3. Clone the Kyma module git repository as `child`
4. Execute the kyma-cli command in parent directory

```bash
kyma alpha create module \
                  --module-config-file ./child/config.yaml \
                  --path ./child \
                  --registry "************" \
                  --sec-scanners-config ./sec-config.yaml \
                  --module-archive-version-overwrite \
                  --output=moduletemplate.yaml \
                  --registry-cred-selector=*********\
                  --credentials oauth2accesstoken:********
```

**Troubleshooting**

Modify our code and run it from `child` directory
```bash
cd child

kyma alpha create module \
                  --module-config-file ./config.yaml \
                  --registry "************" \
                  --sec-scanners-config ./sec-config.yaml \
                  --module-archive-version-overwrite \
                  --output=moduletemplate.yaml \
                  --registry-cred-selector=*********\
                  --credentials oauth2accesstoken:********
```

### PR DESCRIPTION
**Pull request by nesmabadr**
**Description**

Changes proposed in this pull request:

- Fix repoUrl for parent-child git structure

**Related issue(s)**
Resolves #1765

### CODE REVIEW

File: pkg/module/build.go [hunk 1]
```diff
@@ -90,7 +90,15 @@ func CreateArchive(fs vfs.FileSystem, path, gitRemote string, def *Definition, i
 func addSources(ctx cpi.Context, cd *ocm.ComponentDescriptor, def *Definition, gitRemote string) error {
 	if strings.HasSuffix(def.Source, ".git") {
 		gitSource := gitsource.NewGitSource()
-		src, err := gitSource.FetchSource(ctx, def.Source, def.Repo, def.Version, gitRemote)
+		if def.Repo == "" {
+			var repo string
+			var err error
+			if repo, err = gitSource.DetermineRepositoryURL(gitRemote, def.Source); err != nil {
```
Comment (ruanxin) [inline pkg/module/build.go:96]: I like you intended to extract this `DetermineRepositoryURL` out of `FetchSource`, but please consider rewrite this condition and value assign a bit shorter.

for example, you can try to refactor this `DetermineRepositoryURL` to accept `def.Repo` as parameter, directly return and assign to def.Repo if it's not empty.
```
var err error
if def.Repo, err = gitSource.DetermineRepositoryURL(gitRemote, def.Repo, def.Source); err != nil {
  return err
}
```

File: pkg/module/gitsource/git.go [hunk 2]
```diff
@@ -53,8 +47,8 @@ func (g GitSource) FetchSource(ctx cpi.Context, path, repo, version, gitRemote s
 	}, nil
 }
 
-func (g GitSource) determineRepositoryURL(gitRemote string) (string, error) {
-	r, err := git.PlainOpen(".")
+func (g GitSource) DetermineRepositoryURL(gitRemote string, repoPath string) (string, error) {
```
Comment (ruanxin) [inline pkg/module/gitsource/git.go:50]: btw, I covered this test in e2e test setup https://github.com/kyma-project/cli/pull/1768/files#r1329956985

Comment (ruanxin) [inline pkg/module/gitsource/git.go:50]:
```suggestion
func (g GitSource) DetermineRepositoryURL(gitRemote, repoPath string) (string, error) {
```

File: pkg/module/build.go (hunk 1 above)
Comment (ruanxin) [reply pkg/module/build.go:96]: can you verify if htis def.Repo have value? by looking at the [place](https://github.com/kyma-project/cli/blob/dfbb1aa16491bc5b8e9f5a722c37f3ddd6e450bd/pkg/module/resources.go#L252) it get assigned, seems that `p.Repo` also an empty one.

If it's true, then we can even remove this `def.Repo`

Comment (ruanxin) [reply pkg/module/build.go]: after checking this PROJECT file, I think we don't need this `def.Repo`, basically
1. The `Repo` is the repository this module repository, the user run against kubebuilder will anyway run CLI inside module repo, it makes no sense to read it from `PROJECT` file.
2. After remove this `def.Repo`, we are make sure the `DetermineRepositoryURL` use repoPath as the single source of truth.
3. This kubebuilder will deprecated soon, this `def.Repo` will removed anyway.

**Review by ruanxin — APPROVED** [review]
