### PR TITLE
Fix hints and messages

### LINKED ISSUE #2733: Improve hints format
**Description**

Error hints should be in one consistent format. The proposition is to start all hints from `to <what you want> do <what you need to add>`.

```bash
kyma-dev module add 012oqwdooadws
Error:
  unknown module name

Error Details:
  012oqwdooadws not found in the catalog of available modules

Hints:
  - make sure you provide valid module name and channel (or version)
  - list available modules by calling the `kyma module catalog` command
  - pull available modules by calling the `kyma module pull` command
  - if you want to add a community module, use the `--origin` flag
```

### PR DESCRIPTION
**Pull request by grego952**
**Description**

Changes proposed in this pull request:

- Improve CLI hints for the unknown module
- Delete sidebar.md

**Related issue(s)**
Fixes #2733

### CODE REVIEW

File: internal/registry/image.go [hunk 1]
```diff
@@ -44,9 +44,9 @@ func importImage(ctx context.Context, imageName string, pushFunc PushFunc, utils
 	localImage, err := imageFromInternalRegistry(ctx, imageName, utils)
 	if err != nil {
 		return "", clierror.Wrap(err,
-			clierror.New("failed to load image from local docker daemon",
-				"make sure docker daemon is running",
-				"make sure the image exists in the local docker daemon",
+			clierror.New("failed to load image from the local Docker daemon",
+				"make sure Docker daemon is running",
```
Comment (IwonaLanger) [inline internal/registry/image.go]:
```suggestion
				"make sure the Docker daemon is running",
```

File: internal/registry/image.go [hunk 2]
```diff
@@ -44,9 +44,9 @@ func importImage(ctx context.Context, imageName string, pushFunc PushFunc, utils
 	localImage, err := imageFromInternalRegistry(ctx, imageName, utils)
 	if err != nil {
 		return "", clierror.Wrap(err,
-			clierror.New("failed to load image from local docker daemon",
-				"make sure docker daemon is running",
-				"make sure the image exists in the local docker daemon",
+			clierror.New("failed to load image from the local Docker daemon",
```
Comment (IwonaLanger) [inline internal/registry/image.go]:
```suggestion
			clierror.New("failed to load the image from the local Docker daemon",
```

Comment (IwonaLanger) [reply internal/registry/image.go]: The same occurs in the next doc.

File: internal/registry/image.go (hunk 1 above)
Comment (IwonaLanger) [reply internal/registry/image.go]: The same occurs in the next doc.

File: internal/cmd/alpha/kubeconfig/generate.go [hunk 3]
```diff
@@ -153,7 +153,7 @@ func (cfg *generateConfig) validate() clierror.Error {
 		// check if request token is provided
 		return clierror.New(
 			"ACTIONS_ID_TOKEN_REQUEST_TOKEN env variable is required if --id-token-request-url flag or ACTIONS_ID_TOKEN_REQUEST_URL env were provided",
-			"make sure you're running the command in Github Actions environment",
+			"make sure you're running the command in GitHub Actions environment",
```
Comment (IwonaLanger) [inline internal/cmd/alpha/kubeconfig/generate.go]: 'make sure' is used very often in these docs. Please consider replacing it with 'ensure'.

**Review by anoipm — APPROVED** [review]
