### PR TITLE
cmd alpha enable module: Add Channel Input Validation

### LINKED ISSUE #1577: kyma enable module command should validate channel.
**Description**

If enable module command give non exists channel, it will indicate patch success.
The next command which gives a correct channel will not overwrite this wrong channel, and still indicate patch success.

**Expected result**

enable module should validate if the given channel is valid.

**Steps to reproduce**
First given a run channel
```
kyma alpha enable module keda -c wrongchannel -n kcp-system -k default-kyma
```
it will show patch success
```
Modules patched! (22ms)
```

**Troubleshooting**

### PR DESCRIPTION
**Pull request by LeelaChacha**
**Description**

Changes proposed in this pull request:
- Channel is validated by checking against all available ModuleTemplates for the module to be enabled.

**Related issue(s)**

Closes #1577

### CODE REVIEW

File: cmd/kyma/alpha/enable/module/module.go [hunk 1]
```diff
@@ -122,11 +122,25 @@ func (cmd *command) run(ctx context.Context, l *zap.SugaredLogger, moduleName st
...
+	templates, err := moduleInteractor.GetAllModuleTemplatesOfModule(ctx, moduleName)
+	if err != nil {
+		return err
+	}
+	channelToLookup := cmd.opts.Channel
+	if channelToLookup == "" {
+		channelToLookup = kymaChannel
+	}
+	if !doesChannelExist(templates, channelToLookup) {
+		return errors.Errorf("The Channel [%s] does not exist for the ModuleTemplate [%s]\n"+
```
Comment (jakobmoellersap) [inline cmd/kyma/alpha/enable/module/module.go:139]:
```suggestion
		return fmt.Errorf("the channel [%s] does not exist for the ModuleTemplate [%s]\n"+
```
Nice error message! But try to keep it consistent with go errors and do not use line-breaks if possible

**Review by jakobmoellersap — CHANGES_REQUESTED** [review]
LGTM, maybe write a test case for your enable/disable logic. Other than that just small style things like the usage of our default error functions and error formatting.

**Review by jakobmoellersap — APPROVED** [review]
